// UI strings for the document library page, the analytics section and the admin upload flow.

export const documentCopy = {
  vi: {
    nav: "Bản đồ địa chất KCN",
    eyebrow: "Khảo sát địa chất khu công nghiệp",
    title: "Bản đồ hồ sơ địa chất khu công nghiệp Việt Nam",
    intro:
      "Chọn vùng hoặc bấm vào tỉnh trên bản đồ để xem các khu công nghiệp đã có dữ liệu, kèm hồ sơ khảo sát địa chất và sơ đồ mặt bằng của từng khu.",
    kpi: {
      documents: "hồ sơ tài liệu",
      geology: "hồ sơ khảo sát địa chất",
      provinces: "tỉnh/thành",
      zones: "khu công nghiệp"
    },
    tabs: { label: "Khu vực nội dung", map: "Bản đồ & hồ sơ", records: "Danh mục hồ sơ", insights: "Phân tích" },
    regionAll: "Toàn quốc",
    mapLegend: "Mật độ tài liệu",
    mapMode: { label: "Kiểu bản đồ", vector: "Bản đồ vector", google: "Google Maps" },
    mapHint: "Bấm vào tỉnh có màu để xem chi tiết",
    mapNoData: "Chưa có dữ liệu",
    zoom: { label: "Phóng to / thu nhỏ", zoomIn: "Phóng to", zoomOut: "Thu nhỏ", reset: "Về mặc định" },
    noApiKey: "Chưa có Google Maps API key — đang dùng bản đồ SVG nội bộ (vẫn bấm được vào từng tỉnh).",
    provincePanel: {
      zones: "Khu công nghiệp",
      documents: "Tài liệu",
      readiness: "Độ đầy đủ dữ liệu",
      complete: "KCN đủ dữ liệu",
      coverageColumn: "Dữ liệu",
      countColumn: "Hồ sơ",
      openRecords: "Xem hồ sơ",
      zonesShort: "KCN",
      completeShort: "Đủ dữ liệu",
      mergedInto: "Sau sáp nhập 01/07/2025 thuộc",
      lastUpdate: "Cập nhật gần nhất",
      empty: "Chưa có tài liệu nào cho tỉnh này.",
      allZones: "Tất cả KCN",
      provincesAxis: "Số tỉnh",
      otherDocuments: "Hồ sơ cấp tỉnh",
      close: "Đóng"
    },
    coverage: {
      complete: "Đủ sơ đồ + địa chất",
      "map-only": "Chỉ có sơ đồ",
      "geology-only": "Chỉ có địa chất",
      sparse: "Dữ liệu rời rạc"
    },
    filters: {
      category: "Nhóm tài liệu",
      kind: "Định dạng",
      all: "Tất cả",
      search: "Tìm theo tên tài liệu, KCN, tỉnh…",
      hostedOnly: "Chỉ hồ sơ xem được ngay",
      reset: "Xóa lọc",
      loadMore: "Xem thêm",
      results: "kết quả"
    },
    card: {
      open: "Mở tài liệu",
      download: "Tải về",
      onRequest: "Bản đầy đủ cấp theo yêu cầu",
      noPreview: "Không có bản xem trước"
    },
    viewer: { close: "Đóng", openNewTab: "Mở trong tab mới", download: "Tải về" },
    analytics: {
      eyebrow: "Phân tích tự động",
      title: "Bức tranh dữ liệu địa chất theo vùng và tỉnh",
      intro:
        "Mọi con số dưới đây được tính trực tiếp từ bộ hồ sơ hiện có. Bấm “Phân tích bằng AI” để nhận nhận định tự động dựa trên đúng các số này.",
      byProvince: "Tài liệu theo tỉnh",
      byProvinceNote: "12 tỉnh có nhiều hồ sơ nhất, tô màu theo vùng.",
      byCategory: "Cấu trúc nhóm tài liệu",
      byCategoryNote: "Tỷ lệ giữa hồ sơ khảo sát địa chất và sơ đồ mặt bằng khu công nghiệp.",
      coverage: "Độ phủ dữ liệu KCN",
      coverageNote: "Mỗi KCN được xếp theo việc có sơ đồ mặt bằng và/hoặc hồ sơ địa chất.",
      readiness: "So sánh ba vùng",
      readinessNote: "So sánh tương đối giữa các vùng: số tài liệu, số KCN, số KCN có đủ dữ liệu.",
      byYear: "Hồ sơ theo năm",
      byYearNote: "Số hồ sơ theo năm cập nhật gần nhất.",
      narrativeTitle: "Nhận định",
      aiButton: "Phân tích bằng AI",
      aiLoading: "Đang phân tích…",
      aiDisabled: "Tính năng nhận định bằng AI hiện đang tắt.",
      aiSource: "Nguồn nhận định",
      risks: "Rủi ro dữ liệu",
      nextActions: "Việc cần làm tiếp"
    },
    admin: {
      title: "Quản trị",
      login: "Đăng nhập admin",
      logout: "Đăng xuất",
      password: "Mật khẩu admin",
      submit: "Đăng nhập",
      loggedIn: "Đã đăng nhập admin",
      upload: "Tải tài liệu lên",
      dropzone: "Kéo tệp vào đây hoặc bấm để chọn",
      analyzing: "Đang phân loại…",
      suggestion: "Đề xuất phân loại",
      region: "Vùng",
      province: "Tỉnh/thành",
      zone: "Khu công nghiệp",
      category: "Nhóm tài liệu",
      title2: "Tiêu đề",
      start: "Bắt đầu tải lên",
      uploading: "Đang tải lên",
      done: "Đã tải lên xong",
      failed: "Tải lên thất bại",
      notConfigured: "Server chưa cấu hình ADMIN_PASSWORD.",
      hint: "Tài liệu tải lên sẽ được gắn thẻ vùng/tỉnh/KCN và hiện ngay trên bản đồ."
    }
  },
  en: {
    nav: "Industrial park geology",
    eyebrow: "Industrial park geotechnical surveys",
    title: "Geotechnical record map of Vietnam's industrial parks",
    intro:
      "Pick a region or click a province on the map to see the industrial parks with data, together with their geotechnical survey reports and site layouts.",
    kpi: {
      documents: "records",
      geology: "geotechnical surveys",
      provinces: "provinces",
      zones: "industrial parks"
    },
    tabs: { label: "Sections", map: "Map & records", records: "Records", insights: "Insights" },
    regionAll: "Nationwide",
    mapLegend: "Document density",
    mapMode: { label: "Map style", vector: "Vector map", google: "Google Maps" },
    mapHint: "Click a coloured province for detail",
    mapNoData: "No data yet",
    zoom: { label: "Zoom", zoomIn: "Zoom in", zoomOut: "Zoom out", reset: "Reset view" },
    noApiKey: "No Google Maps API key — using the built-in SVG map (provinces are still clickable).",
    provincePanel: {
      zones: "Industrial parks",
      documents: "Documents",
      readiness: "Data completeness",
      complete: "Parks with full data",
      coverageColumn: "Data",
      countColumn: "Records",
      openRecords: "View records",
      zonesShort: "Parks",
      completeShort: "Complete",
      mergedInto: "After the 01/07/2025 merger, part of",
      lastUpdate: "Last updated",
      empty: "No documents for this province yet.",
      allZones: "All parks",
      provincesAxis: "Provinces",
      otherDocuments: "Province-level records",
      close: "Close"
    },
    coverage: {
      complete: "Layout + geology",
      "map-only": "Layout only",
      "geology-only": "Geology only",
      sparse: "Sparse"
    },
    filters: {
      category: "Category",
      kind: "Format",
      all: "All",
      search: "Search by document, park, province…",
      hostedOnly: "Openable now",
      reset: "Clear filters",
      loadMore: "Show more",
      results: "results"
    },
    card: {
      open: "Open",
      download: "Download",
      onRequest: "Full report available on request",
      noPreview: "No preview available"
    },
    viewer: { close: "Close", openNewTab: "Open in new tab", download: "Download" },
    analytics: {
      eyebrow: "Automatic analysis",
      title: "The geotechnical data picture by region and province",
      intro:
        "Every number below is computed from the actual record set. Use “Analyse with AI” for an automatic read-out over exactly these numbers.",
      byProvince: "Documents per province",
      byProvinceNote: "Top 12 provinces, coloured by region.",
      byCategory: "Category mix",
      byCategoryNote: "Split between geotechnical surveys and industrial park layouts.",
      coverage: "Industrial park coverage",
      coverageNote: "Each park is bucketed by whether it has a layout map and/or a geotechnical record.",
      readiness: "Regions compared",
      readinessNote: "Relative comparison: records, parks, parks with complete data.",
      byYear: "Records by year",
      byYearNote: "Number of records by most recent update year.",
      narrativeTitle: "Read-out",
      aiButton: "Analyse with AI",
      aiLoading: "Analysing…",
      aiDisabled: "AI commentary is currently switched off.",
      aiSource: "Commentary source",
      risks: "Data risks",
      nextActions: "Next actions"
    },
    admin: {
      title: "Administration",
      login: "Admin sign-in",
      logout: "Sign out",
      password: "Admin password",
      submit: "Sign in",
      loggedIn: "Signed in as admin",
      upload: "Upload documents",
      dropzone: "Drop files here or click to browse",
      analyzing: "Classifying…",
      suggestion: "Suggested classification",
      region: "Region",
      province: "Province",
      zone: "Industrial park",
      category: "Category",
      title2: "Title",
      start: "Start upload",
      uploading: "Uploading",
      done: "Uploaded",
      failed: "Upload failed",
      notConfigured: "ADMIN_PASSWORD is not configured on the server.",
      hint: "Uploads are tagged with region/province/park and appear on the map immediately."
    }
  },
  ja: {
    nav: "工業団地の地盤資料",
    eyebrow: "工業団地の地盤調査",
    title: "ベトナム工業団地 地盤資料マップ",
    intro:
      "地域を選ぶか地図上の省をクリックすると、資料のある工業団地と、その地盤調査報告書・配置図が表示されます。",
    kpi: {
      documents: "件の資料",
      geology: "件の地盤調査資料",
      provinces: "省・市",
      zones: "工業団地"
    },
    tabs: { label: "セクション", map: "地図と資料", records: "資料一覧", insights: "分析" },
    regionAll: "全国",
    mapLegend: "資料の密度",
    mapMode: { label: "地図の種類", vector: "ベクター地図", google: "Google Maps" },
    mapHint: "色のついた省をクリックすると詳細",
    mapNoData: "資料なし",
    zoom: { label: "拡大・縮小", zoomIn: "拡大", zoomOut: "縮小", reset: "初期表示に戻す" },
    noApiKey: "Google Maps API キーがないため内蔵 SVG 地図を表示しています（省はクリック可能）。",
    provincePanel: {
      zones: "工業団地",
      documents: "資料",
      readiness: "データ充足度",
      complete: "データが揃った団地",
      coverageColumn: "データ",
      countColumn: "件数",
      openRecords: "資料を見る",
      zonesShort: "団地",
      completeShort: "充足",
      mergedInto: "2025/07/01 の統合後の所属",
      lastUpdate: "最終更新",
      empty: "この省の資料はまだありません。",
      allZones: "すべての団地",
      provincesAxis: "省の数",
      otherDocuments: "省レベルの資料",
      close: "閉じる"
    },
    coverage: {
      complete: "配置図＋地盤",
      "map-only": "配置図のみ",
      "geology-only": "地盤のみ",
      sparse: "資料が少ない"
    },
    filters: {
      category: "資料区分",
      kind: "形式",
      all: "すべて",
      search: "資料名・団地・省で検索…",
      hostedOnly: "すぐ閲覧できる資料のみ",
      reset: "条件をクリア",
      loadMore: "さらに表示",
      results: "件"
    },
    card: {
      open: "開く",
      download: "ダウンロード",
      onRequest: "全文は要望に応じて提供します",
      noPreview: "プレビューなし"
    },
    viewer: { close: "閉じる", openNewTab: "新しいタブで開く", download: "ダウンロード" },
    analytics: {
      eyebrow: "自動分析",
      title: "地域・省別の地盤データ全体像",
      intro: "以下の数値はすべて実際の資料から算出しています。「AI で分析」を押すと、この数値に基づく所見が自動生成されます。",
      byProvince: "省別の資料数",
      byProvinceNote: "資料が多い上位 12 省（色は地域）。",
      byCategory: "資料区分の構成",
      byCategoryNote: "地盤調査資料と工業団地配置図の比率。",
      coverage: "工業団地のデータ充足",
      coverageNote: "配置図・地盤資料の有無で各団地を分類。",
      readiness: "地域の比較",
      readinessNote: "資料数・団地数・データが揃った団地数の相対比較。",
      byYear: "年別の資料数",
      byYearNote: "最終更新年ごとの資料件数。",
      narrativeTitle: "所見",
      aiButton: "AI で分析",
      aiLoading: "分析中…",
      aiDisabled: "AI による所見は現在オフです。",
      aiSource: "所見の生成元",
      risks: "データ上のリスク",
      nextActions: "次のアクション"
    },
    admin: {
      title: "管理",
      login: "管理者ログイン",
      logout: "ログアウト",
      password: "管理者パスワード",
      submit: "ログイン",
      loggedIn: "管理者としてログイン中",
      upload: "資料をアップロード",
      dropzone: "ここにドロップ、またはクリックして選択",
      analyzing: "分類中…",
      suggestion: "分類の提案",
      region: "地域",
      province: "省・市",
      zone: "工業団地",
      category: "資料区分",
      title2: "タイトル",
      start: "アップロード開始",
      uploading: "アップロード中",
      done: "完了",
      failed: "失敗",
      notConfigured: "サーバーに ADMIN_PASSWORD が設定されていません。",
      hint: "アップロードした資料は地域・省・団地のタグが付き、すぐ地図に表示されます。"
    }
  }
};
